// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkCQ5meE173XJMPgAf6hGAhikU6HzlKtI',
    appId: '1:282198732334:web:c7ceac6eb1575cf62279bf',
    messagingSenderId: '282198732334',
    projectId: 'style-avenue-fb8f4',
    authDomain: 'style-avenue-fb8f4.firebaseapp.com',
    storageBucket: 'style-avenue-fb8f4.appspot.com',
    measurementId: 'G-FYFLZFGS9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALI7NMM_pZ84TvncKMSWxpqYpB39qSVC8',
    appId: '1:282198732334:android:c54d0b7ba99f305a2279bf',
    messagingSenderId: '282198732334',
    projectId: 'style-avenue-fb8f4',
    storageBucket: 'style-avenue-fb8f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyJREwzzcmrmQTjH4HjE5yp9qQbr04i1I',
    appId: '1:282198732334:ios:2342af0d0516b24a2279bf',
    messagingSenderId: '282198732334',
    projectId: 'style-avenue-fb8f4',
    storageBucket: 'style-avenue-fb8f4.appspot.com',
    androidClientId: '282198732334-v2haacecoctjob551bpi5e5s2c49q9jf.apps.googleusercontent.com',
    iosClientId: '282198732334-489i4hjm5vs9uti80v2lpvd312ba8rc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyJREwzzcmrmQTjH4HjE5yp9qQbr04i1I',
    appId: '1:282198732334:ios:2342af0d0516b24a2279bf',
    messagingSenderId: '282198732334',
    projectId: 'style-avenue-fb8f4',
    storageBucket: 'style-avenue-fb8f4.appspot.com',
    androidClientId: '282198732334-v2haacecoctjob551bpi5e5s2c49q9jf.apps.googleusercontent.com',
    iosClientId: '282198732334-489i4hjm5vs9uti80v2lpvd312ba8rc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkCQ5meE173XJMPgAf6hGAhikU6HzlKtI',
    appId: '1:282198732334:web:e9f222ecf25ba32f2279bf',
    messagingSenderId: '282198732334',
    projectId: 'style-avenue-fb8f4',
    authDomain: 'style-avenue-fb8f4.firebaseapp.com',
    storageBucket: 'style-avenue-fb8f4.appspot.com',
    measurementId: 'G-Z0WZ6BQ5BB',
  );

}